import { test } from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { startStubServer } from "./stub-server.mjs";

const run = promisify(execFile);
const script = fileURLToPath(new URL("./checklist.mjs", import.meta.url));

const TODO_ITEM = "https://github.com/ravendb/ravendb/pull/22439";
const SHORT_ITEM = "https://github.com/ravendb/ravendb/pull/2358";
const IN_PROGRESS_ITEM = "https://github.com/ravendb/ravendb/pull/23581";
const NO_NODE_ITEM = "https://github.com/ravendb/ravendb/commit/0123456789abcdef0123456789abcdef01234567";
const UNKNOWN_ITEM = "https://github.com/ravendb/ravendb/pull/23600";
const NODE_PR = "https://github.com/ravendb/ravendb-nodejs-client/pull/597";

const DESCRIPTION = [
    "Items to port, generated by ravendb-client-migration.",
    "",
    "### 7.2.6",
    "- [PR #22439](https://github.com/ravendb/ravendb/pull/22439) RavenDB-22293 Use JsonPatch `RavenDB-22293-PR22439.patch`",
    "  - [ ] node.js",
    "  - [x] python",
    "  - [ ] java",
    "- [PR #2358](https://github.com/ravendb/ravendb/pull/2358) RavenDB-1 Short number `RavenDB-1-PR2358.patch`",
    "  - [ ] node.js",
    "  - [ ] python",
    "  - [ ] java",
    "- [PR #23581](https://github.com/ravendb/ravendb/pull/23581) RavenDB-22083 Report compilation errors (carrier) `RavenDB-22083-PR23581.patch`",
    "  - [ ] node.js: [PR #597](https://github.com/ravendb/ravendb-nodejs-client/pull/597)",
    "  - [ ] python",
    "  - [ ] java",
    "- [commit 0123456789](https://github.com/ravendb/ravendb/commit/0123456789abcdef0123456789abcdef01234567) RavenDB-7070 fixed compilation `RavenDB-7070-commit0123456789.patch`",
    "  - [ ] python",
    "  - [ ] java",
    "- [PR #23600](https://github.com/ravendb/ravendb/pull/23600) RavenDB-23000 Something `RavenDB-23000-PR23600.patch`",
    "  - [x] node.js: see RDBC-1200",
    "",
].join("\n");

function fakeYouTrack(state) {
    return (request) => {
        const [path] = request.url.split("?");
        if (state.status) return { status: state.status, json: { error: "Forbidden" } };
        if (!state.issue || path !== `/api/issues/${state.issue.idReadable}`) return { status: 404, json: { error: "Not Found" } };
        if (request.method === "POST") {
            state.issue.description = JSON.parse(request.body).description;
            return { json: { idReadable: state.issue.idReadable } };
        }
        return { json: state.issue };
    };
}

const checklist = (server, args, env = {}) => run(process.execPath, [script, ...args], {
    env: { ...process.env, YOUTRACK_URL: server.url, YOUTRACK_TOKEN: "perm:test", ...env },
});

async function checklistFails(server, args, env) {
    try {
        await checklist(server, args, env);
    } catch (err) {
        assert.equal(err.code, 1);
        return err;
    }
    assert.fail("expected a non-zero exit code");
}

const posts = (server) => server.requests.filter((request) => request.method === "POST").length;

async function withIssue(description, fn) {
    const state = { issue: { idReadable: "RDBC-1128", description } };
    const server = await startStubServer(fakeYouTrack(state));
    try {
        await fn(server, state);
    } finally {
        await server.close();
    }
}

test("link turns a todo node.js line into an in-progress line and leaves everything else as is", async () => {
    await withIssue(DESCRIPTION, async (server, state) => {
        const { stderr } = await checklist(server, ["link", "--issue", "https://issues.example/issue/RDBC-1128/title", "--item", TODO_ITEM, "--pr", NODE_PR]);
        const expected = DESCRIPTION.replace(
            "`RavenDB-22293-PR22439.patch`\n  - [ ] node.js\n",
            "`RavenDB-22293-PR22439.patch`\n  - [ ] node.js: [PR #597](https://github.com/ravendb/ravendb-nodejs-client/pull/597)\n",
        );
        assert.equal(state.issue.description, expected);
        assert.match(stderr, /Task RDBC-1128:   - \[ \] node\.js ->   - \[ \] node\.js: \[PR #597\]/);
        assert.ok(server.requests.every((request) => request.url.includes("fields=")), "every request must select fields");
    });
});

test("done ticks an in-progress line and keeps its link", async () => {
    await withIssue(DESCRIPTION, async (server, state) => {
        await checklist(server, ["done", "--issue", "RDBC-1128", "--item", IN_PROGRESS_ITEM]);
        const expected = DESCRIPTION.replace(
            "  - [ ] node.js: [PR #597](https://github.com/ravendb/ravendb-nodejs-client/pull/597)",
            "  - [x] node.js: [PR #597](https://github.com/ravendb/ravendb-nodejs-client/pull/597)",
        );
        assert.equal(state.issue.description, expected);
    });
});

test("na marks the item whose URL is a prefix of another item's URL, and only that one", async () => {
    await withIssue(DESCRIPTION, async (server, state) => {
        await checklist(server, ["na", "--issue", "RDBC-1128", "--item", SHORT_ITEM, "--reason", "version bump only"]);
        const expected = DESCRIPTION.replace(
            "`RavenDB-1-PR2358.patch`\n  - [ ] node.js\n",
            "`RavenDB-1-PR2358.patch`\n  - [x] node.js: n/a (version bump only)\n",
        );
        assert.equal(state.issue.description, expected);
    });
});

test("keeps CRLF line endings", async () => {
    const crlf = DESCRIPTION.replace(/\n/g, "\r\n");
    await withIssue(crlf, async (server, state) => {
        await checklist(server, ["link", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--pr", NODE_PR]);
        const expected = crlf.replace(
            "`RavenDB-22293-PR22439.patch`\r\n  - [ ] node.js\r\n",
            "`RavenDB-22293-PR22439.patch`\r\n  - [ ] node.js: [PR #597](https://github.com/ravendb/ravendb-nodejs-client/pull/597)\r\n",
        );
        assert.equal(state.issue.description, expected);
    });
});

test("refuses a transition from the wrong state and shows the current line", async () => {
    await withIssue(DESCRIPTION, async (server, state) => {
        const doneOnTodo = await checklistFails(server, ["done", "--issue", "RDBC-1128", "--item", TODO_ITEM]);
        assert.match(doneOnTodo.stderr, /Error: cannot done .*pull\/22439: node\.js line is "  - \[ \] node\.js"/);

        const linkOnInProgress = await checklistFails(server, ["link", "--issue", "RDBC-1128", "--item", IN_PROGRESS_ITEM, "--pr", NODE_PR]);
        assert.match(linkOnInProgress.stderr, /node\.js line is "  - \[ \] node\.js: \[PR #597\]/);

        const unknown = await checklistFails(server, ["na", "--issue", "RDBC-1128", "--item", UNKNOWN_ITEM, "--reason", "server only"]);
        assert.match(unknown.stderr, /node\.js line is "  - \[x\] node\.js: see RDBC-1200"/);

        assert.equal(posts(server), 0);
        assert.equal(state.issue.description, DESCRIPTION);
    });
});

test("reports an item that is missing, duplicated, or has no node.js line", async () => {
    await withIssue(DESCRIPTION, async (server) => {
        const missing = await checklistFails(server, ["done", "--issue", "RDBC-1128", "--item", "https://github.com/ravendb/ravendb/pull/1"]);
        assert.match(missing.stderr, /Error: item https:\/\/github\.com\/ravendb\/ravendb\/pull\/1 not found/);

        const noNode = await checklistFails(server, ["na", "--issue", "RDBC-1128", "--item", NO_NODE_ITEM, "--reason", "server only"]);
        assert.match(noNode.stderr, /Error: item .*commit\/0123456789abcdef0123456789abcdef01234567 has no node\.js line/);
        assert.equal(posts(server), 0);
    });
    const duplicated = `${DESCRIPTION}\n### 7.2.7\n- [PR #22439](https://github.com/ravendb/ravendb/pull/22439) Again \`RavenDB-22293-PR22439.patch\`\n  - [ ] node.js\n`;
    await withIssue(duplicated, async (server) => {
        const err = await checklistFails(server, ["link", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--pr", NODE_PR]);
        assert.match(err.stderr, /Error: item .*pull\/22439 appears 2 times/);
        assert.equal(posts(server), 0);
    });
});

test("dry run reads the issue and prints the change without writing", async () => {
    await withIssue(DESCRIPTION, async (server, state) => {
        const { stderr } = await checklist(server, ["na", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--reason", "server only", "--dry-run"]);
        assert.match(stderr, /\[dry-run\] Task RDBC-1128:   - \[ \] node\.js ->   - \[x\] node\.js: n\/a \(server only\)/);
        assert.equal(posts(server), 0);
        assert.equal(state.issue.description, DESCRIPTION);
    });
});

test("rejects bad arguments and a missing token before any request", async () => {
    await withIssue(DESCRIPTION, async (server) => {
        const cases = [
            [["link", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--pr", "https://github.com/ravendb/ravendb/pull/597"], /link needs --pr/],
            [["link", "--issue", "RDBC-1128", "--item", TODO_ITEM], /link needs --pr/],
            [["done", "--issue", "RDBC-1128", "--item", IN_PROGRESS_ITEM, "--pr", NODE_PR], /--pr is only valid with link/],
            [["na", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--reason", "see `x`"], /na needs --reason/],
            [["na", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--reason", "[x]"], /na needs --reason/],
            [["na", "--issue", "RDBC-1128", "--item", TODO_ITEM], /na needs --reason/],
            [["link", "--issue", "new", "--item", TODO_ITEM, "--pr", NODE_PR], /Invalid --issue "new"/],
            [["link", "--issue", "RDBC-1128", "--item", "https://github.com/ravendb/ravendb-nodejs-client/pull/1", "--pr", NODE_PR], /Invalid --item/],
            [["merge", "--issue", "RDBC-1128", "--item", TODO_ITEM], /first argument must be link, done or na/],
            [["done", "--issue", "RDBC-1128"], /Required: --issue/],
            [["na", "--issue", "RDBC-1128", "--item", TODO_ITEM, "--reason", "--dry-run"], /Missing value for --reason/],
        ];
        for (const [args, message] of cases) {
            const err = await checklistFails(server, args);
            assert.match(err.stderr, message, args.join(" "));
        }
        const noToken = await checklistFails(server, ["done", "--issue", "RDBC-1128", "--item", IN_PROGRESS_ITEM], { YOUTRACK_TOKEN: "" });
        assert.match(noToken.stderr, /YOUTRACK_TOKEN is not set/);
        assert.equal(server.requests.length, 0);
    });
});

test("reports a missing issue and a rejected token with the server response", async () => {
    await withIssue(DESCRIPTION, async (server) => {
        const missing = await checklistFails(server, ["done", "--issue", "RDBC-9", "--item", IN_PROGRESS_ITEM]);
        assert.match(missing.stderr, /Error: issue RDBC-9 not found/);
    });
    const server = await startStubServer(fakeYouTrack({ status: 403 }));
    try {
        const err = await checklistFails(server, ["done", "--issue", "RDBC-1128", "--item", IN_PROGRESS_ITEM]);
        assert.match(err.stderr, /Error: YouTrack token rejected \(HTTP 403\): \{"error":"Forbidden"\}/);
    } finally {
        await server.close();
    }
});
